#cloud-config
package_upgrade: true
packages:
  - fontconfig
  - openjdk-17-jre
  - gnupg
  - software-properties-common
  - curl
runcmd:
  - wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - apt-get update
  - apt-get install -y jenkins
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  - apt-get update
  - apt-get install -y terraform
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - systemctl start jenkins
  - systemctl enable jenkins